# Generated by Django 3.0.5 on 2020-06-08 09:00

import account.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='-', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(default='-', max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(default='-', max_length=50, verbose_name='Отчество')),
                ('organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Организация')),
                ('place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('data_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Мужской'), ('f', 'Женский')], max_length=1, null=True, verbose_name='Пол')),
                ('phone', models.CharField(max_length=20, validators=[account.validators.validate_phone_number], verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True, validators=[account.validators.validate_phone_number])),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='Кол-во отправленных сообщений')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_staff', models.BooleanField(default=False)),
                ('phone', models.CharField(error_messages={'unique': 'Пользователь с таким номером уже сущесвтует'}, max_length=15, unique=True, validators=[account.validators.validate_phone_number], verbose_name='Номер телефона')),
                ('email', models.EmailField(error_messages={'unique': 'Пользователь с таким email уже сущесвтует'}, max_length=254, unique=True, verbose_name='Email')),
                ('customer', models.OneToOneField(error_messages={'unique': 'Такой клиент уже привязан к пользователю'}, on_delete=django.db.models.deletion.CASCADE, to='account.Customer', verbose_name='Клиент')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
