# Generated by Django 3.0.5 on 2020-06-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='-', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='-', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(default='-', max_length=50, verbose_name='Отчество'),
        ),
    ]
