# Generated by Django 3.0.5 on 2020-06-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200603_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
