# Generated by Django 3.0.5 on 2020-05-26 15:36

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200526_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользователь с таким email уже сущесвтует'}, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='phone',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким номером уже сущесвтует'}, max_length=15, unique=True, validators=[account.validators.validate_phone_number], verbose_name='Номер телефона'),
        ),
    ]
