# Generated by Django 3.0.5 on 2020-05-13 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('list_of_hashtag', models.CharField(blank=True, max_length=255, null=True, verbose_name='Хэштэги')),
                ('short_name', models.CharField(max_length=255, verbose_name='Короткий текст')),
                ('body', models.TextField(verbose_name='Тело новости')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Картинка')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тэга')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Post_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Post')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Tag')),
            ],
            options={
                'verbose_name': 'Новость - тэг',
                'verbose_name_plural': 'Новость - тэг',
            },
        ),
    ]
