# Generated by Django 3.0.5 on 2020-04-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='list_of_hashtag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Хэштэги'),
        ),
    ]
