# Generated by Django 3.0.5 on 2020-06-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=0, verbose_name='Статус'),
        ),
    ]
