# Generated by Django 3.0.5 on 2020-06-15 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20200615_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 15, 13, 37, 313887, tzinfo=utc)),
        ),
    ]
