# Generated by Django 3.0.5 on 2020-05-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.AddField(
            model_name='customer',
            name='data_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
