# Generated by Django 3.0.5 on 2020-05-07 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200504_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='FIO',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
