# Generated by Django 3.0.5 on 2020-05-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200525_1821'),
        ('main', '0003_auto_20200521_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
