# Generated by Django 3.0.5 on 2020-05-08 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='FIO',
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
