# Generated by Django 3.0.5 on 2020-04-27 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('Book_code', models.AutoField(primary_key=True, serialize=False, verbose_name='Код брони')),
                ('number_of_peaple', models.IntegerField(default=0, max_length=4, verbose_name='Кол-во жильцов')),
                ('check_in_date', models.DateField(verbose_name='Дата заселения')),
                ('date_of_eviction', models.DateField(verbose_name='Дата выселения')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('conditions', models.TextField(verbose_name='Условия')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_place', models.IntegerField(verbose_name='Кол-во мест')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Category', verbose_name='Номер категории')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Команты',
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='Customer_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='Номер брони')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
            ],
            options={
                'verbose_name': 'Список жителей',
                'verbose_name_plural': 'Списки жителей',
                'ordering': ['book_id'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Room', verbose_name='Номер комнаты'),
        ),
    ]
