# Generated by Django 3.0.5 on 2020-04-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_peaple',
            field=models.IntegerField(default=0, verbose_name='Кол-во жильцов'),
        ),
    ]
