# Generated by Django 3.0.5 on 2020-05-25 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('book', '0002_auto_20200513_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_book',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Customer'),
        ),
    ]
