# Generated by Django 3.0.5 on 2020-04-27 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200427_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_peaple',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Кол-во жильцов'),
        ),
    ]
