# Generated by Django 3.0.5 on 2020-04-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200427_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Бронь', 'verbose_name_plural': 'Брони'},
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Номер комнаты'),
        ),
    ]
