# Generated by Django 3.0.5 on 2020-05-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200430_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='paid',
        ),
        migrations.AddField(
            model_name='book',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержедено'),
        ),
    ]
