# Generated by Django 3.0.5 on 2020-05-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20200502_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='additional_information',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
