# Generated by Django 3.0.5 on 2020-05-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_additional_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='number_of_peaple',
            new_name='number_of_people',
        ),
    ]
