# Generated by Django 3.0.5 on 2020-05-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20200507_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_book',
            name='phone',
        ),
    ]
